# Vagrant.configure("2") do |config|
#   config.vm.define "vm1" do |vm1|
#     vm1.vm.box = "centos/7"
#     vm1.vm.hostname = "vm5"
#     vm1.vm.network "private_network", ip: "192.168.33.15"
#   end

#   config.vm.define "vm2" do |vm2|
#     vm2.vm.box = "centos/7"
#     vm2.vm.hostname = "vm2"
#     vm2.vm.network "private_network", ip: "192.168.33.12"
#   end

#   config.vm.define "vm3" do |vm3|
#     vm3.vm.box = "centos/7"
#     vm3.vm.hostname = "vm3"
#     vm3.vm.network "private_network", ip: "192.168.33.13"
#   end
# end


# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
