---
- name: Install Apache on VM
  hosts: all
  become: true
  tasks:
    - name: Install Apache web server
      yum:
        name: httpd
        state: present
      tags:
        - apache

    - name: Start Apache service
      service:
        name: httpd
        state: started
      tags:
        - apache
